### PR TITLE
Added enchants

### PR DESCRIPTION
**Pull request by IshaanRao**
- Added Enchant Capability
- Added Sharpness enchant
- Added GUI for sharpness
- probably fixed some bugs I don't remember

### CODE REVIEW

**Comment by underscorelior** [comment]
Maybe move the Apply green clay to the left, and the red one to the right

**Comment by IshaanRao** [comment]
Right being the common hand of most people in the world has a better connotation because humans hate minorities. Similarly adding things has a positive connotation compared to the denotation with removing things. This would make the right side more fit for something with a positive connotation like the add button.

**Comment by underscorelior** [comment]
Kinda true but it's mostly always left is yes right is no, yes minorities have skill issues

We could fuck with the players, and have it opposite, like many bad uis are (or we can flip the colors for even more evil)

**Review by underscorelior — APPROVED** [review]
Thanks for fixing that, approved, pr yourself

**Pull request merged**
